name: foldtree

channel_priority: strict
channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - pip
  - setuptools
  - foldseek
  - t-coffee
  - snakedeploy
  - snakefmt
  - toytree=2.0.1
  - snakemake>=7.8.0
  - iqtree
  - muscle
  - mafft
  - quicktree
  - python=3.10
  - fasttree=2.1.11
  - clustalo=1.2.4
  - iqtree
  - pandas
  - scipy
  - biopython
  - pycairo
  - numpy
  - tqdm
  - wget
  - statsmodels
  - toyplot
  - requests
  - ujson
  - click
